### ISSUE TITLE
No binary release for Rocky Linux 9 (RHEL 9)

### ISSUE THREAD

**Issue by kenta2** [B-Lang-org/bsc#767]
The primary mechanism we use build [bsc releases](https://github.com/B-Lang-org/bsc/releases) is [LXC](https://wiki.debian.org/LXC).  We are currently unable to create a Rocky Linux 9 LXC container with networking: https://github.com/lxc/lxc/issues/4531

As an alternative to LXC, another method we tried was QEMU (under libvirt), using the "GenericCloud-Base" image from https://wiki.rockylinux.org/rocky/image/#about-cloud-images

First, we generated `config.iso` was generated using `cloud-localds` (in the cloud-init ecosystem) from the following `config.yaml` (following directions at https://stafwag.github.io/blog/blog/2019/03/03/howto-use-centos-cloud-images-with-cloud-init/ ):

```
#cloud-config
package_upgrade: false
users:
  - name: myusername
    groups: wheel
    lock_passwd: false
    passwd: (elided)
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa (elided)
```

Then, attempted to start the image with:

```
sudo virt-install --memory 8192 --vcpus 2 --name bscrockynine --disk ~/doingrocky/Rocky-9-GenericCloud-Base-9.5-20241118.0.x86_64.qcow2,device=disk --disk ~/doingrocky/config.iso,device=cdrom --osinfo rocky9 --virt-type qemu --graphics none --network default --import
```

The result was nothing emitted on console.  I am not very familiar with libvirt, so cannot understand what is going wrong.  However, this host is able to run Centos 7 images with QEMU from https://cloud.centos.org/centos/7/images/ .
